experiment_dir: train_output
save_checkpoint: true
validate_using_ema: true
max_epochs: 80
n_forward_steps: 1
inference:
  n_forward_steps: 7300  # 5 years
  forward_steps_in_memory: 50
  loader:
    start_indices:
      first: 0
      n_initial_conditions: 4
      interval: 1460  # 1 year
    dataset:
      data_path: /data1/DATA_ARCHIVE/Reanalysis/ERA5_new/data_360x180/daily/multi_lev/t
      file_pattern: "*.nc"
      # fill_nans:
      #   method: constant
      #   value: 0.0
    num_data_workers: 4
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace
  entity: your_wandb_entity
train_loader:
  batch_size: 4
  num_data_workers: 4
  prefetch_factor: 4
  dataset:
    data_path: /data1/DATA_ARCHIVE/Reanalysis/ERA5_new/data_360x180/daily/multi_lev/t
    file_pattern: "*.nc"
    # fill_nans:
    #   method: constant
    #   value: 0.0
validation_loader:
  batch_size: 16
  num_data_workers: 4
  prefetch_factor: 4
  dataset:
    data_path: /data1/DATA_ARCHIVE/Reanalysis/ERA5_new/data_360x180/daily/multi_lev/t
    file_pattern: "*.nc"
    subset:
      step: 5
    # fill_nans:
    #   method: constant
    #   value: 0.0
optimization:
  enable_automatic_mixed_precision: true
  lr: 0.0001
  optimizer_type: Adam  # can switch to FusedAdam if using GPU
stepper:
  loss:
    type: MSE
  step:
    type: single_module
    config:
      builder:
        type: SphericalFourierNeuralOperatorNet
        config:
          embed_dim: 384
          filter_type: linear
          hard_thresholding_fraction: 1.0
          use_mlp: true
          normalization_layer: instance_norm
          num_layers: 8
          operator_type: dhconv
          scale_factor: 1
          separable: false
      normalization:
        network:
          global_means_path: /home/yjlee/ace-main/Ace_data_construction/out_360x180/daily/_stats/centering.nc
          global_stds_path: /home/yjlee/ace-main/Ace_data_construction/out_360x180/daily/_stats/scaling-full-field.nc
          # fill_nans_on_normalize: true
        loss:
          global_means_path: /home/yjlee/ace-main/Ace_data_construction/out_360x180/daily/_stats/centering.nc
          global_stds_path: /home/yjlee/ace-main/Ace_data_construction/out_360x180/daily/_stats/scaling-full-field.nc
          # fill_nans_on_normalize: true
      ocean:
        surface_temperature_name: surface_temperature
        ocean_fraction_name: ocean_fraction
      corrector:
        conserve_dry_air: true
        moisture_budget_correction: null
      in_names:
      - land_fraction
      - ocean_fraction
      - sea_ice_fraction
      - DSWRFtoa
      - HGTsfc
      - PRESsfc
      - surface_temperature
      - air_temperature_0 # _0 denotes the top most layer of the atmosphere
      - air_temperature_1
      - air_temperature_2
      - air_temperature_3
      - air_temperature_4
      - air_temperature_5
      - air_temperature_6
      - air_temperature_7
      - air_temperature_8
      - air_temperature_9
      - air_temperature_10
      - air_temperature_11
      - air_temperature_12
      - specific_total_water_0
      - specific_total_water_1
      - specific_total_water_2
      - specific_total_water_3
      - specific_total_water_4
      - specific_total_water_5
      - specific_total_water_6
      - specific_total_water_7
      - specific_total_water_8
      - specific_total_water_9
      - specific_total_water_10
      - specific_total_water_11
      - specific_total_water_12
      - eastward_wind_0
      - eastward_wind_1
      - eastward_wind_2
      - eastward_wind_3
      - eastward_wind_4
      - eastward_wind_5
      - eastward_wind_6
      - eastward_wind_7
      - eastward_wind_8
      - eastward_wind_9
      - eastward_wind_10
      - eastward_wind_11
      - eastward_wind_12
      - northward_wind_0
      - northward_wind_1
      - northward_wind_2
      - northward_wind_3
      - northward_wind_4
      - northward_wind_5
      - northward_wind_6
      - northward_wind_7
      - northward_wind_8
      - northward_wind_9
      - northward_wind_10
      - northward_wind_11
      - northward_wind_12
      out_names:
      - PRESsfc
      - surface_temperature
      - air_temperature_0
      - air_temperature_1
      - air_temperature_2
      - air_temperature_3
      - air_temperature_4
      - air_temperature_5
      - air_temperature_6
      - air_temperature_7
      - air_temperature_8
      - air_temperature_9
      - air_temperature_10
      - air_temperature_11
      - air_temperature_12
      - specific_total_water_0
      - specific_total_water_1
      - specific_total_water_2
      - specific_total_water_3
      - specific_total_water_4
      - specific_total_water_5
      - specific_total_water_6
      - specific_total_water_7
      - specific_total_water_8
      - specific_total_water_9
      - specific_total_water_10
      - specific_total_water_11
      - specific_total_water_12
      - eastward_wind_0
      - eastward_wind_1
      - eastward_wind_2
      - eastward_wind_3
      - eastward_wind_4
      - eastward_wind_5
      - eastward_wind_6
      - eastward_wind_7
      - eastward_wind_8
      - eastward_wind_9
      - eastward_wind_10
      - eastward_wind_11
      - eastward_wind_12
      - northward_wind_0
      - northward_wind_1
      - northward_wind_2
      - northward_wind_3
      - northward_wind_4
      - northward_wind_5
      - northward_wind_6
      - northward_wind_7
      - northward_wind_8
      - northward_wind_9
      - northward_wind_10
      - northward_wind_11
      - northward_wind_12